[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
edition = "2018"
name = "brz"
version = "0.1.0"

[dependencies]
common_failures = "*"
failure = "*"
ropey = "*"
termion = "*"
default = "*"
structopt = "*"

[profile.dev]
# stuff's too slow in `debug`
opt-level = 1
